# Generated by Django 5.2.12 on 2026-04-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('valor', models.CharField(blank=True, default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to=settings.AUTH_USER_MODEL)),
                ('turno_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_actual', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instante', models.DateTimeField(auto_now_add=True)),
                ('celda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tresenraya.celda')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresenraya.partida')),
            ],
            options={
                'ordering': ['instante'],
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tablero', to='tresenraya.partida')),
            ],
        ),
        migrations.AddField(
            model_name='celda',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresenraya.tablero'),
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresenraya.partida')),
            ],
            options={
                'unique_together': {('partida', 'simbolo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='celda',
            unique_together={('tablero', 'fila', 'columna')},
        ),
    ]
