# Generated by Django 5.2.12 on 2026-04-04 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tresenraya', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugadores',
            new_name='Jugador',
        ),
    ]
